language: go

go_import_path: github.com/TheThingsNetwork/gateway-connector-bridge

sudo: required

services:
  - docker

go:
  - "1.12.x"

env:
  global:
  - GOPROXY=https://proxy.golang.org
  - GO111MODULE=on

cache:
  directories:
    - $HOME/gopath/pkg/mod

install:
  - make deps
  - make cover-deps

before_script:
  - docker run -d -p 127.0.0.1:6379:6379 redis
  - docker run -d -p 127.0.0.1:1883:1883 -p 127.0.0.1:5672:5672 thethingsnetwork/rabbitmq

script:
  - make test
  - make fmt
  - make vet

after_success:
  - make coveralls
